//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace NT.Models
{
    /// <summary>
    /// 实体类users。(属性说明自动提取数据库字段的描述信息)
    /// </summary>

    [Serializable]
    public partial class Users
    {
        #region Model
        private string _SerialNumber;
        private string _UserID;
        private string _UserName;
        private string _PassWord;
        private string _Email;
        private string _CardId;
        private bool? _Status;
        private string _Memo;

        public string SerialNumber
        {
            get { return _SerialNumber; }
            set
            {
                this._SerialNumber = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UserID
        {
            get { return _UserID; }
            set
            {
                this._UserID = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string UserName
        {
            get { return _UserName; }
            set
            {
                this._UserName = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string PassWord
        {
            get { return _PassWord; }
            set
            {
                this._PassWord = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Email
        {
            get { return _Email; }
            set
            {
                this._Email = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string CardId
        {
            get { return _CardId; }
            set
            {
                this._CardId = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public bool? Status
        {
            get { return _Status; }
            set
            {
                this._Status = value;
            }
        }
        /// <summary>
        /// 
        /// </summary>
        public string Memo
        {
            get { return _Memo; }
            set
            {
                this._Memo = value;
            }
        }
        #endregion 
    }
}